### ISSUE TITLE
Repair or Engage sometimes fails

### ISSUE THREAD

**Issue by Greg-Boggs** [Tsunder/SGPvP#16]
When using "Engage or Repair", the script has been failing to repair even when the user is below minimum armor count and has bots on board.

**Comment by Tsunder** [comment]
Can you copy-paste the error message, if there is one? (From F12 / console)

AFAIK there is a one action per second limit on attacking (not sure if it only applies to pvp type attacks) and repairing with bots and moving (not sure if this extends to drug usage/planet repair or other moving-like actions (wormhole jumping? cloaking?)).

AFAIK i have not touched code relating to repair/engage, so this would be a very rare and/or old bug.

**Comment by Tsunder** [comment]
hypothesis 1: something to do with the script's memory (storage) of the pilot's armor points, maybe not updating with the *latest* armor level on the pilot somehow (page loading too late such that the script goes into next page before it saves storage? some other race condition?)


hypothesis 2: it tries to repair but fails somehow?

**Comment by Greg-Boggs** [comment]
Github won't let me open a PR from dday25 to yours for some reason, but here's the fixes needed:

https://github.com/dday25/SGPvP
